"""Added the is_logged_in column

Revision ID: a17684b2dfc0
Revises: 0c74a4f92be1
Create Date: 2026-10-05 22:23:23.757299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17684b2dfc0'
down_revision: Union[str, Sequence[str], None] = '0c74a4f92be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engineer', sa.Column('is_logged_in', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_engineer_engineer_email'), 'engineer', ['engineer_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineer_engineer_email'), table_name='engineer')
    op.drop_column('engineer', 'is_logged_in')
    # ### end Alembic commands ###
